### ISSUE TITLE
The paddleMovement script is bugged

### ISSUE THREAD

**Issue by Jaaz-** [bhardy0630/D-Pong#3] opened 2019-04-14 21:59 UTC
The movement only allows movement on the x-axis, where we need the paddles to move on the y-axis.

I think this may have to do with the characterController2D script,
which was intended for sidescrolling platformers.

**Comment by bhardy0630** [comment] 2019-04-14 22:03
Bug confirmed in milestone build 1.

Assigning to myself.

**Comment by bhardy0630** [comment] 2019-04-15 00:06
The source of the issue is as follows:

Vector3 targetVelocity = new Vector2(move * 10f, m_Rigidbody2D.velocity.y);

The preceding snippet was taken from a sidescroller type tutorial. To resolve the issue, these arguments were flipped:

move * 10f

m_Rigidbody2D.velocity.y

And the last was changed to:

m_Rigidbody2D.velocity.**x**

resulting in a change of movement axis.

Resolved.

**Closed by bhardy0630** 2019-04-15 00:06 UTC
